version: '3.8'

services:
  app:
    build: .
    container_name: secure-auth-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authdb
      SPRING_DATASOURCE_USERNAME: authuser
      SPRING_DATASOURCE_PASSWORD: authpass
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: secure-auth-postgres
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: secure-auth-redis
    restart: always

volumes:
  pgdata:
